# Generated by Django 6.0.5 on 2026-05-26 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar_visibility',
            field=models.CharField(choices=[('everyone', "Hammaga ko'rinadi"), ('private_only', 'Faqat shaxsiy chatda yozganlarga')], default='everyone', max_length=20),
        ),
    ]
