# Generated by Django 5.2.14 on 2026-05-31 01:11

from django.db import migrations, models
from django.utils import timezone


def backfill_email_verified_at(apps, schema_editor):
    Profile = apps.get_model("accounts", "Profile")
    now = timezone.now()
    for profile in Profile.objects.filter(email_verified_at__isnull=True).iterator():
        profile.email_verified_at = profile.created_at or now
        profile.save(update_fields=["email_verified_at"])


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_push_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_moderator',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('review_approved', 'Sharh tasdiqlandi'), ('review_rejected', 'Sharh rad etildi'), ('review_pending', 'Sharh moderatsiyada'), ('review_liked', 'Sharh yoqdi'), ('chat_unread', "O'qilmagan xabar"), ('report_received', 'Shikoyat qabul qilindi'), ('report_updated', 'Shikoyat holati yangilandi')], max_length=32),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('applicant', 'Abituriyent'), ('student', 'Talaba')], default='applicant', max_length=20),
        ),
        migrations.RunPython(backfill_email_verified_at, migrations.RunPython.noop),
    ]
