# Generated by Django 5.2.14 on 2026-05-31 01:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0022_community_chat'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='messagereport',
            name='unique_chat_message_report_per_user',
        ),
        migrations.RemoveConstraint(
            model_name='messagereport',
            name='unique_direct_message_report_per_user',
        ),
        migrations.RenameIndex(
            model_name='messagereport',
            new_name='universitie_created_16bb47_idx',
            old_name='universities_created_6e2a0d_idx',
        ),
        migrations.RenameIndex(
            model_name='reviewreport',
            new_name='universitie_created_d8e02e_idx',
            old_name='universitie_created_6e8b0d_idx',
        ),
        migrations.AddField(
            model_name='messagereport',
            name='moderator_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='messagereport',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_message_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='messagereport',
            name='status',
            field=models.CharField(choices=[('pending', "Ko'rib chiqish kutilmoqda"), ('in_review', "Ko'rib chiqilmoqda"), ('resolved', 'Hal qilindi'), ('dismissed', 'Rad etildi')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='messagereport',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='reviewreport',
            name='moderator_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='reviewreport',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_review_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reviewreport',
            name='status',
            field=models.CharField(choices=[('pending', "Ko'rib chiqish kutilmoqda"), ('in_review', "Ko'rib chiqilmoqda"), ('resolved', 'Hal qilindi'), ('dismissed', 'Rad etildi')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='reviewreport',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='messagereport',
            name='reason',
            field=models.CharField(choices=[('insult', 'Haqorat'), ('abuse', "Zo'ravonlik"), ('other', 'Boshqa')], max_length=20),
        ),
        migrations.AddIndex(
            model_name='messagereport',
            index=models.Index(fields=['status', '-created_at'], name='universitie_status_3daac1_idx'),
        ),
        migrations.AddIndex(
            model_name='reviewreport',
            index=models.Index(fields=['status', '-created_at'], name='universitie_status_61e69f_idx'),
        ),
    ]
