# Generated by Django 5.2.14 on 2026-05-31 01:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0023_trust_safety'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='messagereport',
            constraint=models.UniqueConstraint(condition=models.Q(('chat_message__isnull', False)), fields=('reporter', 'chat_message'), name='unique_chat_message_report_per_user'),
        ),
        migrations.AddConstraint(
            model_name='messagereport',
            constraint=models.UniqueConstraint(condition=models.Q(('direct_message__isnull', False)), fields=('reporter', 'direct_message'), name='unique_direct_message_report_per_user'),
        ),
    ]
