# Generated by Django 5.2.14 on 2026-07-10 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("universities", "0042_fix_article_cover_image_paths"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProfanityBlockDaily",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("day", models.DateField(db_index=True)),
                ("scope", models.CharField(db_index=True, default="reviews", max_length=32)),
                ("matched", models.CharField(db_index=True, max_length=64)),
                ("strategy", models.CharField(blank=True, default="", max_length=32)),
                ("count", models.PositiveIntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Profanity block (kunlik)",
                "verbose_name_plural": "Profanity blocklar (kunlik)",
            },
        ),
        migrations.AddIndex(
            model_name="profanityblockdaily",
            index=models.Index(fields=["day", "scope"], name="profanity_day_scope_idx"),
        ),
        migrations.AddConstraint(
            model_name="profanityblockdaily",
            constraint=models.UniqueConstraint(
                fields=("day", "scope", "matched", "strategy"),
                name="uniq_profanity_block_daily",
            ),
        ),
    ]
