import { useMemo } from "react";

function useDashboardChatLayout({
  isDesktop,
  activeSection,
  chatListTab,
  chatPanel,
  isCompactLayout,
}) {
  const isPrivateChatLayout =
    isDesktop && activeSection === "chats" && chatListTab === "private";

  const isGroupChatLayout =
    isDesktop && activeSection === "chats" && chatPanel === "group";

  const isWideChatLayout = isPrivateChatLayout || isGroupChatLayout;

  const chatColumnEqualHeightClass = isCompactLayout
    ? "h-fit max-h-[calc(100dvh-11rem)] self-start md:max-h-[calc(100vh-10rem)]"
    : "md:flex md:h-[calc(100dvh-11.5rem)] md:max-h-[calc(100dvh-11.5rem)] md:flex-col md:overflow-hidden";

  const chatListScrollClass = isCompactLayout
    ? "chat-messages-scroll mt-4 max-h-[min(28rem,calc(100dvh-17rem))] space-y-1 overflow-y-auto overscroll-contain pr-1"
    : "chat-messages-scroll mt-4 min-h-0 flex-1 space-y-1 overflow-y-auto overscroll-contain pr-1";

  const chatMessagesAreaClass = isCompactLayout
    ? "chat-messages-scroll h-[calc(100dvh-14rem)] min-h-[200px] overflow-y-auto overflow-x-hidden overscroll-contain"
    : "chat-messages-scroll min-h-0 flex-1 overflow-y-auto overflow-x-hidden overscroll-contain";

  const chatPanelInnerClass = isCompactLayout
    ? "flex flex-col"
    : "flex min-h-0 flex-1 flex-col overflow-hidden";

  const chatSectionGridClass = isCompactLayout
    ? "grid-cols-1"
    : isWideChatLayout
      ? "lg:grid-cols-[minmax(280px,30%)_minmax(0,1fr)] lg:gap-4 xl:gap-5"
      : "lg:grid-cols-[minmax(0,340px)_minmax(0,1fr)] xl:grid-cols-[420px_1fr]";

  return {
    isWideChatLayout,
    chatSectionGridClass,
    chatColumnEqualHeightClass,
    chatListScrollClass,
    chatMessagesAreaClass,
    chatPanelInnerClass,
  };
}

export function useDashboardChatSectionValue({
  chatUi,
  activeSection,
  isDesktop,
  isCompactLayout,
  isWideChat,
  chatListTab,
  chatPanel,
  selectedThreadId,
  composerFocusToken,
  mobileChatScreen,
  totalJoinedUnread,
  totalPrivateUnread,
  universitySearch,
  setUniversitySearch,
  privateThreadList,
  filteredUniversities,
  selectedUniversityId,
  joinedUniversityIds,
  getUniversityTypingUsers,
  selectedThread,
  selectedUniversity,
  hasJoinedSelectedChat,
  privatePinnedMessage,
  handleUnpinPrivateMessage,
  directMessages,
  handlePrivateReaction,
  handlePinPrivateMessage,
  handleUnpinGroupMessage,
  reactingMessageId,
  privateTypingUsers,
  privateMessage,
  setPrivateMessage,
  notifyPrivateTyping,
  sendPrivateChatMessage,
  isPrivateSending,
  privateMessageRefs,
  groupPinnedMessage,
  groupMessages,
  groupMessageRefs,
  handleGroupReaction,
  handlePinGroupMessage,
  user,
  groupTypingUsers,
  groupMessage,
  setGroupMessage,
  notifyGroupTyping,
  sendGroupChatMessage,
  isGroupSending,
  isGroupJoining,
  editingChatMessage,
  openEditChatMessage,
  cancelEditChatMessage,
  requestDeleteGroupMessage,
  requestDeletePrivateMessage,
  groupChatTags,
  activeGroupTag,
  setActiveGroupTag,
  isGroupMessagesLoading,
  isPrivateMessagesLoading,
  prefetchGroupMessages,
}) {
  const layout = useDashboardChatLayout({
    isDesktop,
    activeSection,
    chatListTab,
    chatPanel,
    isCompactLayout,
  });

  const { displayedGroupUniversity, isGroupChatHeaderLoading } = chatUi;

  return useMemo(
    () => ({
      ...chatUi,
      isChatUserMuted: chatUi.checkChatUserMuted,
      selectedThreadId,
      composerFocusToken,
      isPhone: isCompactLayout,
      mobileChatScreen,
      chatSectionGridClass: layout.chatSectionGridClass,
      chatColumnEqualHeightClass: layout.chatColumnEqualHeightClass,
      chatListScrollClass: layout.chatListScrollClass,
      chatMessagesAreaClass: layout.chatMessagesAreaClass,
      chatPanelInnerClass: layout.chatPanelInnerClass,
      chatListTab,
      handleChatTabChange: chatUi.handleChatTabChange,
      totalJoinedUnread,
      totalPrivateUnread,
      universitySearch,
      setUniversitySearch,
      privateThreadList,
      filteredUniversities,
      selectedUniversityId,
      joinedUniversityIds,
      getUniversityTypingUsers,
      isWideChatLayout: layout.isWideChatLayout,
      isWideChat,
      chatPanel,
      selectedThread,
      selectedUniversity,
      hasJoinedSelectedChat,
      privatePinnedMessage,
      handleUnpinPrivateMessage,
      directMessages,
      handlePrivateReaction,
      handlePinPrivateMessage,
      handleUnpinGroupMessage,
      reactingMessageId,
      privateTypingUsers,
      privateMessage,
      setPrivateMessage,
      notifyPrivateTyping,
      sendPrivateChatMessage,
      isPrivateSending,
      privateMessageRefs,
      groupPinnedMessage,
      groupMessages,
      groupMessageRefs,
      handleGroupReaction,
      handlePinGroupMessage,
      user,
      groupTypingUsers,
      groupMessage,
      setGroupMessage,
      notifyGroupTyping,
      sendGroupChatMessage,
      isGroupSending,
      isGroupJoining,
      editingChatMessage,
      openEditChatMessage,
      cancelEditChatMessage,
      handleDeleteGroupMessage: requestDeleteGroupMessage,
      handleDeletePrivateMessage: requestDeletePrivateMessage,
      groupChatTags,
      activeGroupTag,
      onSelectGroupTag: chatUi.handleSelectGroupTag,
      onClearGroupTag: () => setActiveGroupTag(""),
      onMuteChatUser: chatUi.handleMuteChatUser,
      onUnblockPrivateChatUser: chatUi.handleUnblockPrivateChatUser,
      onBlockProfileUser: chatUi.handleBlockProfileUser,
      onUnblockProfileUser: chatUi.handleUnblockProfileUser,
      isGroupInfoDetailLoading: chatUi.isGroupInfoDetailLoading,
      isGroupMessagesLoading,
      isPrivateMessagesLoading,
      prefetchGroupMessages,
      displayedGroupUniversity,
      isGroupChatHeaderLoading,
    }),
    [
      chatUi,
      selectedThreadId,
      composerFocusToken,
      isCompactLayout,
      mobileChatScreen,
      layout.chatSectionGridClass,
      layout.chatColumnEqualHeightClass,
      layout.chatListScrollClass,
      layout.chatMessagesAreaClass,
      layout.chatPanelInnerClass,
      chatListTab,
      totalJoinedUnread,
      totalPrivateUnread,
      universitySearch,
      setUniversitySearch,
      privateThreadList,
      filteredUniversities,
      selectedUniversityId,
      joinedUniversityIds,
      getUniversityTypingUsers,
      layout.isWideChatLayout,
      isWideChat,
      chatPanel,
      selectedThread,
      selectedUniversity,
      hasJoinedSelectedChat,
      privatePinnedMessage,
      handleUnpinPrivateMessage,
      directMessages,
      handlePrivateReaction,
      handlePinPrivateMessage,
      handleUnpinGroupMessage,
      reactingMessageId,
      privateTypingUsers,
      privateMessage,
      setPrivateMessage,
      notifyPrivateTyping,
      sendPrivateChatMessage,
      isPrivateSending,
      privateMessageRefs,
      groupPinnedMessage,
      groupMessages,
      groupMessageRefs,
      handleGroupReaction,
      handlePinGroupMessage,
      user,
      groupTypingUsers,
      groupMessage,
      setGroupMessage,
      notifyGroupTyping,
      sendGroupChatMessage,
      isGroupSending,
      isGroupJoining,
      editingChatMessage,
      openEditChatMessage,
      cancelEditChatMessage,
      requestDeleteGroupMessage,
      requestDeletePrivateMessage,
      groupChatTags,
      activeGroupTag,
      setActiveGroupTag,
      isGroupMessagesLoading,
      isPrivateMessagesLoading,
      prefetchGroupMessages,
      displayedGroupUniversity,
      isGroupChatHeaderLoading,
    ]
  );
}
