import { useMemo } from "react";
import { buildDashboardChatLayoutClasses } from "./buildDashboardChatLayoutClasses.js";

function useDashboardChatLayout(args) {
  return buildDashboardChatLayoutClasses(args);
}

export function useDashboardChatSectionValue({
  chatUi,
  activeSection,
  isDesktop,
  isCompactLayout,
  isWideChat,
  chatListTab,
  chatPanel,
  selectedThreadId,
  composerFocusToken,
  mobileChatScreen,
  totalJoinedUnread,
  totalPrivateUnread,
  universitySearch,
  setUniversitySearch,
  privateThreadList,
  filteredUniversities,
  selectedUniversityId,
  joinedUniversityIds,
  getUniversityTypingUsers,
  selectedThread,
  selectedUniversity,
  hasJoinedSelectedChat,
  privatePinnedMessage,
  handleUnpinPrivateMessage,
  directMessages,
  handlePrivateReaction,
  handlePinPrivateMessage,
  handleUnpinGroupMessage,
  reactingMessageId,
  privateTypingUsers,
  privateMessage,
  setPrivateMessage,
  notifyPrivateTyping,
  sendPrivateChatMessage,
  isPrivateSending,
  privateMessageRefs,
  groupPinnedMessage,
  groupMessages,
  groupMessageRefs,
  handleGroupReaction,
  handlePinGroupMessage,
  user,
  groupTypingUsers,
  groupMessage,
  setGroupMessage,
  notifyGroupTyping,
  sendGroupChatMessage,
  isGroupSending,
  isGroupJoining,
  editingChatMessage,
  openEditChatMessage,
  cancelEditChatMessage,
  replyComposePreview,
  openReplyChatMessage,
  cancelReplyChatMessage,
  requestDeleteGroupMessage,
  requestDeletePrivateMessage,
  groupChatTags,
  activeGroupTag,
  setActiveGroupTag,
  isGroupMessagesLoading,
  isPrivateMessagesLoading,
  prefetchGroupMessages,
}) {
  const layout = useDashboardChatLayout({
    isDesktop,
    activeSection,
    chatListTab,
    chatPanel,
    isCompactLayout,
    mobileChatScreen,
  });

  const { displayedGroupUniversity, isGroupChatHeaderLoading } = chatUi;

  return useMemo(
    () => ({
      ...chatUi,
      isChatUserMuted: chatUi.checkChatUserMuted,
      selectedThreadId,
      composerFocusToken,
      isPhone: isCompactLayout,
      mobileChatScreen,
      isImmersiveThread: layout.isImmersiveThread,
      chatSectionGridClass: layout.chatSectionGridClass,
      chatColumnEqualHeightClass: layout.chatColumnEqualHeightClass,
      chatListScrollClass: layout.chatListScrollClass,
      chatMessagesAreaClass: layout.chatMessagesAreaClass,
      chatPanelInnerClass: layout.chatPanelInnerClass,
      chatThreadSurfaceClass: layout.chatThreadSurfaceClass,
      chatComposerBarClass: layout.chatComposerBarClass,
      chatThreadHeaderClass: layout.chatThreadHeaderClass,
      chatListTab,
      handleChatTabChange: chatUi.handleChatTabChange,
      totalJoinedUnread,
      totalPrivateUnread,
      universitySearch,
      setUniversitySearch,
      privateThreadList,
      filteredUniversities,
      selectedUniversityId,
      joinedUniversityIds,
      getUniversityTypingUsers,
      isWideChatLayout: layout.isWideChatLayout,
      isWideChat,
      chatPanel,
      selectedThread,
      selectedUniversity,
      hasJoinedSelectedChat,
      privatePinnedMessage,
      handleUnpinPrivateMessage,
      directMessages,
      handlePrivateReaction,
      handlePinPrivateMessage,
      handleUnpinGroupMessage,
      reactingMessageId,
      privateTypingUsers,
      privateMessage,
      setPrivateMessage,
      notifyPrivateTyping,
      sendPrivateChatMessage,
      isPrivateSending,
      privateMessageRefs,
      groupPinnedMessage,
      groupMessages,
      groupMessageRefs,
      handleGroupReaction,
      handlePinGroupMessage,
      user,
      groupTypingUsers,
      groupMessage,
      setGroupMessage,
      notifyGroupTyping,
      sendGroupChatMessage,
      isGroupSending,
      isGroupJoining,
      editingChatMessage,
      openEditChatMessage,
      cancelEditChatMessage,
      replyComposePreview,
      openReplyChatMessage,
      cancelReplyChatMessage,
      handleDeleteGroupMessage: requestDeleteGroupMessage,
      handleDeletePrivateMessage: requestDeletePrivateMessage,
      groupChatTags,
      activeGroupTag,
      onSelectGroupTag: chatUi.handleSelectGroupTag,
      onClearGroupTag: () => setActiveGroupTag(""),
      onMuteChatUser: chatUi.handleMuteChatUser,
      onUnblockPrivateChatUser: chatUi.handleUnblockPrivateChatUser,
      onBlockProfileUser: chatUi.handleBlockProfileUser,
      onUnblockProfileUser: chatUi.handleUnblockProfileUser,
      isGroupInfoDetailLoading: chatUi.isGroupInfoDetailLoading,
      isGroupMessagesLoading,
      isPrivateMessagesLoading,
      prefetchGroupMessages,
      displayedGroupUniversity,
      isGroupChatHeaderLoading,
    }),
    [
      chatUi,
      selectedThreadId,
      composerFocusToken,
      isCompactLayout,
      mobileChatScreen,
      layout.isImmersiveThread,
      layout.chatSectionGridClass,
      layout.chatColumnEqualHeightClass,
      layout.chatListScrollClass,
      layout.chatMessagesAreaClass,
      layout.chatPanelInnerClass,
      layout.chatThreadSurfaceClass,
      layout.chatComposerBarClass,
      layout.chatThreadHeaderClass,
      chatListTab,
      totalJoinedUnread,
      totalPrivateUnread,
      universitySearch,
      setUniversitySearch,
      privateThreadList,
      filteredUniversities,
      selectedUniversityId,
      joinedUniversityIds,
      getUniversityTypingUsers,
      layout.isWideChatLayout,
      isWideChat,
      chatPanel,
      selectedThread,
      selectedUniversity,
      hasJoinedSelectedChat,
      privatePinnedMessage,
      handleUnpinPrivateMessage,
      directMessages,
      handlePrivateReaction,
      handlePinPrivateMessage,
      handleUnpinGroupMessage,
      reactingMessageId,
      privateTypingUsers,
      privateMessage,
      setPrivateMessage,
      notifyPrivateTyping,
      sendPrivateChatMessage,
      isPrivateSending,
      privateMessageRefs,
      groupPinnedMessage,
      groupMessages,
      groupMessageRefs,
      handleGroupReaction,
      handlePinGroupMessage,
      user,
      groupTypingUsers,
      groupMessage,
      setGroupMessage,
      notifyGroupTyping,
      sendGroupChatMessage,
      isGroupSending,
      isGroupJoining,
      editingChatMessage,
      openEditChatMessage,
      cancelEditChatMessage,
      replyComposePreview,
      openReplyChatMessage,
      cancelReplyChatMessage,
      requestDeleteGroupMessage,
      requestDeletePrivateMessage,
      groupChatTags,
      activeGroupTag,
      setActiveGroupTag,
      isGroupMessagesLoading,
      isPrivateMessagesLoading,
      prefetchGroupMessages,
      displayedGroupUniversity,
      isGroupChatHeaderLoading,
    ]
  );
}
